gText_Birch_Welcome::
	.string "Hey there! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Birch, but everyone \n"
	.string "calls me the Pokémon Professor.\p"
	.string "Pleased to make your acquaintance!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This region, this whole world,\n"
	.string "is full of Pokémon. For example...\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Isn't he a cutie?\p"
	.string "We humans live alongside Pokémon.\n"
	.string "We play with them, we work with them,\l"
	.string "and of course, we battle others\l"
	.string "with them, to test our strength.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "To unravel Pokémon mysteries,\n"
	.string "I've been undertaking research,\l"
	.string "dedicating my life to studying these\l"
	.string "fascinating creatures.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "But that's enough about me!\n"
	.string "Tell me about yourself!\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "And what's your name?$"

gText_Birch_SoItsPlayer::
	.string "Your name's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, gotcha!\p"
	.string "You're {PLAYER}{KUN}, the new kid\n"
	.string "moving to Littleroot, right?\l"
	.string "Perfect!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you.\n"
	.string "Talk to you soon!\p"
	.string "$"
